# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Nikunj Rajesh Lad'
name:             'Nikunj Rajesh Lad'
#tagline:          ''
description:      'Computer Vision Developer and Graduate Teaching Assistant'
#url:              http://vakila.github.io/
baseurl:
# blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Nikunj Rajesh Lad'
  url:            nikunjlad.github.io
  email:          'lad.n@husky.neu.edu'
  github:         'https://github.com/nikunjlad'
  facebook:       'http://www.facebook.com/nikunj.sporty'
  twitter:        'https://twitter.com/LadNikunj'
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/nikunjlad '

paginate:         3
# paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/nikunjlad/nikunjlad.github.io

# Collections
collections:
  - projects
  - talks

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
